module.exports = {

	// Success
	"ERR_SUCCESS"										: {"rc" : 0,	"message" : "success"},
	"ERR_UNKNOWN_ERROR"									: {"rc" : 1,	"message" : "unknown error"},
	"ERR_API_CRASH"										: {"rc" : 2,	"message" : "unhandled error"},

	// API
	"ERR_API_SERVER_IS_NOT_ACTIVE"						: {"rc" : 100,	"message" : "api server is not active"},
	"ERR_INVALID_API_CALL"								: {"rc" : 101,	"message" : "invalid api call"},
	"ERR_MISSING_API_PARAM"								: {"rc" : 102,	"message" : "missing api param"},
	"ERR_NO_PRIVILEGES"									: {"rc" : 103,	"message" : "current user does not have privileges to perform this action"},
	"ERR_NOT_IMPLEMENTED"								: {"rc" : 104,	"message" : "api method is not implemented"},
	"ERR_INVALID_API_PARAM"								: {"rc" : 105,	"message" : "invalid api param"},
	"ERR_INVALID_USER_ROLE"								: {"rc" : 106,	"message" : "invalid user role"},
	"ERR_DEPRECATED_API"								: {"rc" : 107,	"message" : "deprecated api"},
	"ERR_INVALID_API_MODULE"							: {"rc" : 108,	"message" : "invalid api module"},
	"ERR_INVALID_PASSCODE"								: {"rc" : 109,	"message" : "invalid passcode"},
	"ERR_HTTP_ERROR"									: {"rc" : 110,	"message" : "HTTP error"},
	"ERR_DOWNLOAD_ERROR"								: {"rc" : 111,	"message" : "download error"},
	"ERR_INVALID_MODULE_OR_METHOD"						: {"rc" : 112,	"message" : "invalid module or method"},

	// User
	"ERR_INVALID_USER_TOKEN"							: {"rc" : 201,	"message" : "invalid user token"},
	"ERR_USER_NOT_FOUND"								: {"rc" : 202,	"message" : "invalid user or password"},
	"ERR_USER_NOT_EXISTS"								: {"rc" : 203,	"message" : "user does not exist"},
	"ERR_USER_ALREADY_EXISTS"							: {"rc" : 204,	"message" : "user already exists"},
	"ERR_INVALID_USER_TYPE"								: {"rc" : 205,	"message" : "invalid user type"},
	"ERR_INVALID_ACTIVATION_CODE"						: {"rc" : 206,	"message" : "invalid activation code"},
	"ERR_INVALID_FACEBOOK_ACCESS_TOKEN"					: {"rc" : 207,	"message" : "invalid facebook access token"},
	"ERR_INVALID_FACEBOOK_USER_ID"						: {"rc" : 208,	"message" : "invalid facebook user id"},
	"ERR_USER_FACEBOOK_AUTHENTICATION_ERROR"		    : {"rc" : 209,	"message" : "Facebook authentication exception"},
	"ERR_USER_FACEBOOK_AUTHENTICATION_FAILED"		    : {"rc" : 210,	"message" : "Facebook authentication failed"},
	"ERR_USER_FACEBOOK_ERROR_GETTING_PROFILE_PICTURE"  	: {"rc" : 211,	"message" : "Getting facebook profile picture failed",},
	"ERR_USER_FACEBOOK_LOGIN_NOT_ALLOWED"  				: {"rc" : 212,	"message" : "Login with Facebook is not allowed.",},
	"ERR_REQ_FIRST_NAME"								: {"rc" : 213,	"message" : "first name is a required parameter"},
	"ERR_REQ_LAST_NAME"									: {"rc" : 214,	"message" : "last name is a required parameter"},
	"ERR_REQ_EMAIL"										: {"rc" : 215,	"message" : "email is a required parameter"},
	"ERR_REQ_PASSWORD"									: {"rc" : 216,	"message" : "password is a required parameter"},
	"ERR_INVALIDATED_CAPTCHA"							: {"rc" : 217,	"message" : "invalidated captcha"},
	"ERR_ACCOUNT_IS_TEMPORARILY_LOCKED"					: {"rc" : 218,	"message" : "account is temporarily locked"},
	"ERR_INVALID_GOOGLE_USER_ID"						: {"rc" : 219,	"message" : "invalid google user id"},
	"ERR_USER_GOOGLE_AUTHENTICATION_FAILED"			    : {"rc" : 220,	"message" : "Goolge authentication failed"},
	"ERR_USER_GOOGLE_ERROR_GETTING_PROFILE_PICTURE"  	: {"rc" : 221,	"message" : "Getting Google profile picture failed",},
	"ERR_USER_GOOGLE_LOGIN_NOT_ALLOWED"  				: {"rc" : 222,	"message" : "Login with Google is not allowed.",},
	"ERR_INVALID_GOOGLE_ACCESS_TOKEN"					: {"rc" : 223,	"message" : "invalid Google access token"},
	"ERR_INVALID_PHONE_NUMBER"							: {"rc" : 224,	"message" : "invalid phone number"},
	"ERR_INVALID_PHONE_VERIFICATION_TRY_AGAIN"			: {"rc" : 225,	"message" : "invalid phone verification try again"},
	"ERR_INVALID_PHONE_VERIFICATION_SEND_NEW_CODE"		: {"rc" : 226,	"message" : "invalid phone verification send new code"},
	"ERR_INVALID_PHONE_AUTHORIZATION"					: {"rc" : 227,	"message" : "invalid phone authorization"},
	"ERR_USER_PHONE_NOT_FOUND"							: {"rc" : 228,	"message" : "user phone not found"},
	"ERR_INVALID_SOCIAL_AUTHORIZATION"					: {"rc" : 229,	"message" : "invalid social authorization"},
	"ERR_SOCIAL_USER_NOT_FOUND"							: {"rc" : 230,	"message" : "social user not found"},
	"ERR_USER_APPLE_LOGIN_NOT_ALLOWED"  				: {"rc" : 231,	"message" : "Login with Apple is not allowed.",},
	"ERR_INVALID_APPLE_USER_ID"							: {"rc" : 232,	"message" : "invalid Apple user id"},
	"ERR_INVALID_APPLE_ACCESS_TOKEN"					: {"rc" : 233,	"message" : "invalid Apple access token"},
	"ERR_USER_APPLE_AUTHENTICATION_FAILED"			    : {"rc" : 234,	"message" : "Apple authentication failed"},
	"ERR_INVALID_EMAIL_ADDRESS"						    : {"rc" : 235,	"message" : "invalid email address"},
	"ERR_INVALID_EMAIL_VERIFICATION_TRY_AGAIN"			: {"rc" : 236,	"message" : "invalid email verification try again"},
	"ERR_INVALID_EMAIL_VERIFICATION_SEND_NEW_CODE"		: {"rc" : 237,	"message" : "invalid email verification send new code"},
	"ERR_INVALID_EMAIL_AUTHORIZATION"					: {"rc" : 238,	"message" : "invalid email authorization"},
	"ERR_USER_EMAIL_NOT_FOUND"							: {"rc" : 239,	"message" : "user email not found"},
	"ERR_USER_EMAIL_ALREADY_EXISTS"						: {"rc" : 240,	"message" : "user with this email already exists"},
	"ERR_USER_PHONE_ALREADY_EXISTS"						: {"rc" : 241,	"message" : "user with this phone already exists"},
	"ERR_PASSWORD_NOT_MEET_CRITERIA"					: {"rc" : 242,	"message" : $Utils.getPasswordCriteriaError("password must have", "#CHARS# characters", "at least 1 lower case", "at least 1 upper case", "at least 1 number", "at least 1 special character")},
	"ERR_INVALID_VERIFICATION_FACTOR_TYPE"				: {"rc" : 243,	"message" : "Invalid verification factor type"},
	"ERR_INVALID_VERIFICATION_SEND_NEW_CODE"			: {"rc" : 244,	"message" : "Invalid verification send new code"},
	"ERR_NO_ACTION_TO_DO"								: {"rc" : 245,	"message" : "No action to do"},
	"ERR_INVALID_FACTOR_TYPE"							: {"rc" : 246,	"message" : "Invalid factor type"},
	"ERR_INVALID_PASSWORD"								: {"rc" : 247,	"message" : "Invalid password"},
	"ERR_NEW_PASSWORD_CANNOT_BE_SAME_AS_CURRENT"		: {"rc" : 248,	"message" : "The new password cannot be the same as the current password"},

	// Image
	"ERR_IMAGE_NOT_FOUND"								: {"rc" : 301,	"message" : "image not found"},
	"ERR_INVALID_UPLOADED_IMAGE"						: {"rc" : 302,	"message" : "invalid uploaded image"},
	"ERR_INVALID_IMAGE_PARAMS"							: {"rc" : 303,	"message" : "invalid image params"},
	"ERR_INVALID_IMAGE_DATA"							: {"rc" : 304,	"message" : "invalid image data"},
	"ERR_UNSUPPORTED_IMAGE_TYPE"						: {"rc" : 305,	"message" : "unsupported image type"},

	// File
	"ERR_FILE_NOT_FOUND"								: {"rc" : 321,	"message" : "file not found"},
	"ERR_INVALID_UPLOADED_FILE"							: {"rc" : 322,	"message" : "invalid uploaded file"},
	"ERR_INVALID_FILE_PARAMS"							: {"rc" : 323,	"message" : "invalid file params"},
	"ERR_INVALID_FILE_TYPE"								: {"rc" : 324,	"message" : "invalid file type"},
	"ERR_INVALID_FILE_DATA"								: {"rc" : 325,	"message" : "invalid file data"},
	"ERR_INVALID_MULTIPART_UPLOAD_ID"					: {"rc" : 326,	"message" : "invalid multipart upload id"},
	"ERR_INVALID_MULTIPART_UPLOAD_PART_NUM"				: {"rc" : 327,	"message" : "invalid multipart upload part number"},
	"ERR_MISSING_MULTIPART_PARTS"						: {"rc" : 328,	"message" : "missing multipart parts"},
	"ERR_INCONSISTENT_MULTIPART_PARTS"					: {"rc" : 329,	"message" : "inconsistent multipart parts"},
	"ERR_FAILED_TO_WRITE_FILE"							: {"rc" : 330,	"message" : "failed to write file"},
	"ERR_MULTIPART_UPLOAD_PART_NUM_ALREADY_EXIST"		: {"rc" : 331,	"message" : "multipart upload part num already exist"},
	"ERR_INVALID_FILE_NAME"								: {"rc" : 332,	"message" : "invalid file name"},

	// S3
	"ERR_S3_FAILED_TO_SAVE_FILE"						: {"rc" : 341,	"message" : "s3 failed to save file"},
	"ERR_S3_FAILED_TO_CREATE_MULTIPART_UPLOAD"			: {"rc" : 342,	"message" : "s3 failed to create multipart upload"},
	"ERR_S3_FAILED_TO_SAVE_MULTIPART_ITEM"				: {"rc" : 343,	"message" : "s3 failed to save multipart item"},
	"ERR_S3_FAILED_TO_COMPLETE_MULTIPART_UPLOAD"		: {"rc" : 344,	"message" : "s3 failed to complete multipart upload"},
	"ERR_S3_FAILED_TO_GET_FILE"							: {"rc" : 345,	"message" : "s3 failed to get file"},
	"ERR_S3_FAILED_TO_DELETE_FILE"						: {"rc" : 346,	"message" : "s3 failed to delete file"},

	// Services
	"ERR_FAILED_TO_SEND_SMS"							: {"rc" : 361,	"message" : "failed to send sms"},
	"ERR_INVALID_SMS_PROVIDER"							: {"rc" : 362,	"message" : "invalid sms provider"},
	"ERR_NO_EMAIL_PROVIDER_SET"							: {"rc" : 363,	"message" : "no email provider set"},
	"ERR_FAILED_TO_SEND_EMAIL"							: {"rc" : 364,	"message" : "failed to send email"},
	"ERR_FAILED_TO_CREATE_ICAL_EVENT"					: {"rc" : 365,	"message" : "failed to create iCal event"},
	"ERR_JSONDB_INVALID_ID"								: {"rc" : 366,	"message" : "invalid id"},
	"ERR_JSONDB_MISMATCH_IDS_COUNT"						: {"rc" : 367,	"message" : "mismatch ids count"},
	"ERR_JSONDB_INVALID_INDEX"							: {"rc" : 368,	"message" : "invalid index"},
	"ERR_FAILED_TO_ALLOCATE_SHORT_CODE"					: {"rc" : 369,	"message" : "failed to allocate short code"},
	"ERR_INVALID_ACTION_ID"								: {"rc" : 370,	"message" : "Invalid action ID"},
	"ERR_ACTION_STILL_IN_PROGRESS"						: {"rc" : 371,	"message" : "Action still in progress"},
	"ERR_INVALID_LOG_ANALYZER_DATE"						: {"rc" : 372,	"message" : "Invalid date"},

	// DB
	"ERR_DB_GENERAL_ERROR"								: {"rc" : 400,	"message" : "DB general error"},
	"ERR_DB_INSERT_ERROR"								: {"rc" : 401,	"message" : "DB insert error"},
	"ERR_DB_UPDATE_ERROR"								: {"rc" : 402,	"message" : "DB update error"},
	"ERR_DB_DELETE_ERROR"								: {"rc" : 403,	"message" : "DB delete error"},
	"ERR_DB_INVALID_TABLE_NAME"							: {"rc" : 404,	"message" : "DB invalid table name"},
	"ERR_DB_TABLE_PRIMARY_KEY_NOT_SUPPORTED"			: {"rc" : 405,	"message" : "DB table's primary key is not supported"},
	"ERR_DB_INVALID_ROW_ID"								: {"rc" : 406,	"message" : "DB invalid row id"},

	// Cache
	"ERR_CACHE_GENERAL_ERROR"							: {"rc" : 450,	"message" : "cache general error"},
	"ERR_CACHE_INVALID_DATA_COUNT"						: {"rc" : 451,	"message" : "cache put error: invalid data count"},
	"ERR_CACHE_WRITE_FAILED"							: {"rc" : 452,	"message" : "cache put error: failed to write file"},
	"ERR_CACHE_READ_FAILED"								: {"rc" : 453,	"message" : "cache get error: failed to read file"},
	"ERR_CACHE_DELETE_FAILED"							: {"rc" : 454,	"message" : "cache delete error: failed to delete file"},

	// Content

};
